const express=require('express');
const router=express.Router();
const studentController=require('../controller/studentcontroller/studentregistrationandsignup.js');
const jwt=require('../middleware/jwttoken.js');
const studentmw=require('../middleware/jwttoken.js');
const uplaod=require('../middleware/uploadMiddleware.js');
router.post('/studentlogin',studentController.login);
router.post('/studentregister',studentController.checkUserExists,studentController.signup);
router.post('/updatedetails',jwt.authenticateJWT,studentController.updatedetails);
router.post('/userdetails',jwt.authenticateJWT,studentController.userdetails);
router.post('/changepassword',jwt.authenticateJWT,studentController.changePassword);
router.post('/studentlogout',jwt.authenticateJWT,studentController.logout);
router.post('/getProgress',jwt.authenticateJWT,studentController.studentProgress);
router.post('/upcomingRoutes',jwt.authenticateJWT,studentController.upcomingTask);
router.post('/combinedStudentData',jwt.authenticateJWT,studentController.combinedStudentData); 
router.post('/addgoals',jwt.authenticateJWT,studentController.addgoals);
router.post('/removegoals',jwt.authenticateJWT,studentController.removegoals);
router.delete('/removeStudent',studentController.removeStudent);
router.get('/verifyEmail/:verifyToken', studentController.verifyEmail);       
router.post('/resend-verification', studentController.resendVerificationEmail);
module.exports=router;